spring :
  application:
    name: LibraryProject
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: talib123
  liquibase:
    change-log: classpath:migrations/changelog-master.xml
    enabled: true

  mail:
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            todo: elave et pass ve username
    username: ""
    port: 587
    password: ""

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    properties:
