version: '3.8'
services:
  db:
    container_name: postgres-db
    image: postgres:12.20-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=talib123
    ports:
      - '5432:5432'
    volumes:
      - ../../docker-volumes/postgres-db:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  redis:
    container_name: redis-server
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - REDIS_PASSWORD=redis123
    ports:
      - '6379:6379'
    volumes:
      - ../../docker-volumes/redis:/bitnami/redis/data

volumes:
  rabbitmq_data:
